		<!-- FOOTER -->
		<footer class="py-3 mt-4 sviwg-footer">
			<ul class="nav justify-content-center border-bottom pb-3 mb-3">
				<li class="nav-item"><a href="default.asp" class="nav-link px-2 text-muted">Home</a></li>
				<li class="nav-item"><a href="documents.asp" class="nav-link px-2 text-muted">Documents</a></li>
				<li class="nav-item"><a href="accessibility.asp" class="nav-link px-2 text-muted">Accessibility</a></li>
				<li class="nav-item"><a href="contact.asp" class="nav-link px-2 text-muted">Contact</a></li>
			</ul>
			<p class="text-center fs-5">Page last updated: <%=lastUpdated%></p>
			<p class="text-center fs-5">
				Site managed by James Percival (<a href="mailto:sviwg_webmaster@proton.me">sviwg_webmaster@proton.me</a>)
			</p>
			<p class="text-center text-muted">&copy; 2025 <span class="sviwg-sr-abbr">S&nbsp;V&nbsp;I&nbsp;W&nbsp;G</span></p>
		</footer>

	</div>
</body>

</html>