		<!-- FOOTER -->
		<footer class="py-3 mt-4 sviwg-footer text-center">
			<ul class="nav justify-content-center border-bottom pb-3 mb-3">
				<li class="nav-item"><a href="default.asp" class="nav-link px-2 text-muted">Home</a></li>
				<li class="nav-item"><a href="documents.asp" class="nav-link px-2 text-muted">Documents</a></li>
				<li class="nav-item"><a href="accessibility.asp" class="nav-link px-2 text-muted">Accessibility</a></li>
				<li class="nav-item"><a href="contact.asp" class="nav-link px-2 text-muted">Contact</a></li>
			</ul>
			<p class="fs-5">Page last updated: <%=lastUpdated%></p>
			<p class="fs-5">
				Site managed by James Percival (<a href="mailto:sviwg_webmaster@proton.me">sviwg_webmaster@proton.me</a>)
			</p>
			<section class="text-muted">
				<div class="fs-5 mb-2">
					Find us on social media
				</div>
				<a href="https://www.facebook.com/people/Sheffield-Visually-Impaired-walking-group/61572295273366/"
					target="_blank">
					<img class="mb-2" src="images/icons/Facebook_Logo_Primary.png" style='width:40px'
					alt="Facebook logo" title="Facebook">
				</a>
			</section>
			<p class="text-muted">&copy; 2025 <span class="sviwg-sr-abbr">S&nbsp;V&nbsp;I&nbsp;W&nbsp;G</span></p>
		</footer>

	</div>
</body>

</html>